### Import data

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sympy import symbols, solve
import itertools
import yfinance as yf
from sklearn.linear_model import LinearRegression
import math

In [2]:
indexes = yf.download("TSLA KO V SHEL", start="2011-02-01", end="2022-02-01")

[*********************100%***********************]  4 of 4 completed


In [3]:
returns = indexes['Adj Close'].resample('y').ffill().pct_change()
returns

KO      SHEL      TSLA         V
Date                                                             
2011-12-31 00:00:00-05:00       NaN       NaN       NaN       NaN
2012-12-31 00:00:00-05:00  0.065276 -0.009087  0.185924  0.504669
2013-12-31 00:00:00-05:00  0.172331  0.090379  3.441394  0.480564
2014-12-31 00:00:00-05:00  0.052661 -0.012650  0.478495  0.186358
2015-12-31 00:00:00-05:00  0.051399 -0.271207  0.079133  0.191374
2016-12-31 00:00:00-05:00 -0.003571  0.282596 -0.109662  0.013712
2017-12-31 00:00:00-05:00  0.143821  0.310230  0.457017  0.471765
2018-12-31 00:00:00-05:00  0.067735 -0.075133  0.068894  0.164876
2019-12-31 00:00:00-05:00  0.205994  0.077085  0.257001  0.433270
2020-12-31 00:00:00-05:00  0.024691 -0.374393  7.434370  0.171242
2021-12-31 00:00:00-05:00  0.113725  0.284254  0.497556 -0.003149
2022-12-31 00:00:00-05:00  0.030400  0.184332 -0.113609  0.043653

In [4]:
returns = returns[1:]
returns

KO      SHEL      TSLA         V
Date                                                             
2012-12-31 00:00:00-05:00  0.065276 -0.009087  0.185924  0.504669
2013-12-31 00:00:00-05:00  0.172331  0.090379  3.441394  0.480564
2014-12-31 00:00:00-05:00  0.052661 -0.012650  0.478495  0.186358
2015-12-31 00:00:00-05:00  0.051399 -0.271207  0.079133  0.191374
2016-12-31 00:00:00-05:00 -0.003571  0.282596 -0.109662  0.013712
2017-12-31 00:00:00-05:00  0.143821  0.310230  0.457017  0.471765
2018-12-31 00:00:00-05:00  0.067735 -0.075133  0.068894  0.164876
2019-12-31 00:00:00-05:00  0.205994  0.077085  0.257001  0.433270
2020-12-31 00:00:00-05:00  0.024691 -0.374393  7.434370  0.171242
2021-12-31 00:00:00-05:00  0.113725  0.284254  0.497556 -0.003149
2022-12-31 00:00:00-05:00  0.030400  0.184332 -0.113609  0.043653

### Test af numpy cov() og mean() Middelværdi

In [5]:
returns = indexes['Adj Close'].resample('y').ffill().pct_change()
returns = returns[1:]
returns

KO      SHEL      TSLA         V
Date                                                             
2012-12-31 00:00:00-05:00  0.065276 -0.009087  0.185924  0.504669
2013-12-31 00:00:00-05:00  0.172331  0.090379  3.441394  0.480564
2014-12-31 00:00:00-05:00  0.052661 -0.012650  0.478495  0.186358
2015-12-31 00:00:00-05:00  0.051399 -0.271207  0.079133  0.191374
2016-12-31 00:00:00-05:00 -0.003571  0.282596 -0.109662  0.013712
2017-12-31 00:00:00-05:00  0.143821  0.310230  0.457017  0.471765
2018-12-31 00:00:00-05:00  0.067735 -0.075133  0.068894  0.164876
2019-12-31 00:00:00-05:00  0.205994  0.077085  0.257001  0.433270
2020-12-31 00:00:00-05:00  0.024691 -0.374393  7.434370  0.171242
2021-12-31 00:00:00-05:00  0.113725  0.284254  0.497556 -0.003149
2022-12-31 00:00:00-05:00  0.030400  0.184332 -0.113609  0.043653

In [6]:
returns.mean()

KO      0.084042
SHEL    0.044219
TSLA    1.152410
V       0.241667
dtype: float64

In [7]:
np_returns = returns.to_numpy()
np_returns

array([[ 6.52756520e-02, -9.08664550e-03,  1.85924288e-01,
         5.04669355e-01],
       [ 1.72330511e-01,  9.03788750e-02,  3.44139411e+00,
         4.80563997e-01],
       [ 5.26608594e-02, -1.26496372e-02,  4.78494877e-01,
         1.86357803e-01],
       [ 5.13985195e-02, -2.71207260e-01,  7.91331850e-02,
         1.91373911e-01],
       [-3.57125265e-03,  2.82596074e-01, -1.09662130e-01,
         1.37121256e-02],
       [ 1.43821049e-01,  3.10229579e-01,  4.57017111e-01,
         4.71764867e-01],
       [ 6.77348395e-02, -7.51325172e-02,  6.88935445e-02,
         1.64876001e-01],
       [ 2.05994402e-01,  7.70849173e-02,  2.57001189e-01,
         4.33269964e-01],
       [ 2.46913477e-02, -3.74392635e-01,  7.43436995e+00,
         1.71242089e-01],
       [ 1.13724689e-01,  2.84254100e-01,  4.97555592e-01,
        -3.14924922e-03],
       [ 3.04002988e-02,  1.84331785e-01, -1.13609318e-01,
         4.36528646e-02]])

In [8]:
np_returns[1,0]

0.17233051099810148

In [9]:
a,b = np.shape(np_returns)
print(a)
print(b)

11
4


In [10]:
test = np.zeros((1,4))
test

array([[0., 0., 0., 0.]])

In [11]:
test[0,1]

0.0

In [12]:
def mean_value(x):
    """ Takes a dataframe x as input, assuming columns are indexes and rows are values
    Returns a columns vector of mean values for each index
    """
    rows, columns = np.shape(x)
    mean_matrix = np.zeros(columns)
    
    x = x.to_numpy()
    for i in range(columns):
        result = 0
        for j in range(rows):
            result += x[j,i]
        result = result*(1/rows)
        
        mean_matrix[i] = result
    
    return mean_matrix

In [13]:
mean_value(returns)

array([0.0840419 , 0.04421879, 1.15241022, 0.2416667 ])

In [14]:
returns.mean()

KO      0.084042
SHEL    0.044219
TSLA    1.152410
V       0.241667
dtype: float64

In [15]:
test1 = returns.mean().to_numpy()
test1

array([0.0840419 , 0.04421879, 1.15241022, 0.2416667 ])

In [16]:
test2 = mean_value(returns)
test2

array([0.0840419 , 0.04421879, 1.15241022, 0.2416667 ])

In [17]:
for i in range(len(test1)):
    print(math.isclose(test1[i], test2[i]))

True
True
True
True


#### Covariance matrix

In [18]:
def cov_matrix(stock_prices):
    """Takes an numpy array of prices as input then calculates the covariance matrix between the columns
       Returns a covariance matrix between the columns
    """
    
    # Calculate the mean of each stock
    means = np.mean(stock_prices, axis=0)
    
    # Center the data by subtracting the mean from each data point
    centered_data = stock_prices - means
    
    # Calculate the covariance matrix
    covariance_matrix = np.dot(centered_data.T, centered_data) / (centered_data.shape[0] - 1)
    
    return covariance_matrix

In [19]:
manualcov = cov_matrix(returns.to_numpy())

In [20]:
pdcov = returns.cov()

In [21]:
np.allclose(manualcov,pdcov)

True